# Generated by Django 2.2.1 on 2019-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
