# Generated by Django 2.2.1 on 2019-09-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='liked_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_track',
            new_name='track',
        ),
    ]
